# Schema for the configuration files of the form_module module.
form_module.settings:
  type: config_object
  label: 'form_module settings'
  mapping:
    example:
      type: string
      label: 'Example'
